telegram:
  bot:
    token: "8030048287:AAFMbTbPt4r8m-y__b8iFBqrwDJwXDe1rpw"
    name: "LogsParserggbot"
checker:
  url: "http://localhost:8080"
#  url: "${CHECKER_URL}"
spring:
  main:
    banner-mode: off
logging:
  level:
    ru.gnaizel.telegram: debug
    ru.gnaizel.handler: debug
server:
  port: 7979