services:
  checker-service:
    build:
      context: ./CheckerServer
      dockerfile: Dockerfile
    container_name: checker-service
    ports:
      - "8080:8080"
    depends_on:
      - checker-db
    restart: unless-stopped
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://checker-db:5432/logs-checker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  checker-db:
    image: postgres:16.1
    container_name: checker-db
    ports:
      - "2345:5432"
    environment:
      - POSTGRES_DB=logs-checker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  services:
    telegram-bot:
      image: telegram-file-downloader:latest
      build: .
      environment:
        - TELEGRAM_API_ID=your_api_id
        - TELEGRAM_API_HASH=your_api_hash
        - TELEGRAM_PHONE=+1234567890
        - TELEGRAM_CODE=12345
        - DOWNLOAD_DIR=/data/downloads
      volumes:
        - telegram_data:/app/tdlib_db
        - downloads:/data/downloads
      restart: unless-stopped

  volumes:
    telegram_data:
    downloads:

  telegram-bot:
    build:
      context: ./TelegramBot
      dockerfile: Dockerfile
    container_name: telegram-bot
    ports:
      - "9090:9090"
    depends_on:
      - user-db
    restart: unless-stopped
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-db:5432/user-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  user-db:
    image: postgres:16.1
    container_name: user-db
    ports:
      - "3456:5432"
    environment:
      - POSTGRES_DB=user-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
