CREATE TABLE IF NOT EXISTS log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name TEXT NOT NULL,
    original_file_name TEXT NOT NULL,
    file_size DOUBLE PRECISION NOT NULL,
    file_size_unit VARCHAR(20),
    all_line_count BIGINT,
    upload_time TIMESTAMP
);

CREATE TABLE IF NOT EXISTS log_file_in_expect (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id BIGINT NOT NULL REFERENCES log(id)
);