CREATE TABLE IF NOT EXISTS USERS
(
    id
    BIGINT
    GENERATED
    BY
    DEFAULT AS
    IDENTITY
    PRIMARY
    KEY,
    name
    VARCHAR
(
    100
) NOT NULL,
    registration TIMESTAMP NOT NULL,
    telegram_id BIGINT NOT NULL
    );


CREATE TABLE IF NOT EXISTS log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name TEXT NOT NULL,
    original_file_name NOT NULL,
    file_size_in_megabyte DOUBLE PRECISION NOT NULL,
    owner_id BIGINT REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS file_in_expect (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_telegram_id BIGINT NOT NULL REFERENCES users(telegram_id),
  file_id BIGINT NOT NULL REFERENCES log(id)
);
