CREATE TABLE IF NOT EXISTS log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name TEXT NOT NULL,
    original_file_name TEXT NOT NULL,
    file_size_in_megabyte DOUBLE PRECISION NOT NULL,
    owner_id BIGINT  -- Без REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS file_in_expect (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_telegram_id BIGINT NOT NULL,  -- Без REFERENCES users(telegram_id)
    file_id BIGINT NOT NULL REFERENCES log(id)
);