logs-service:
  url: http://logs-service:8080

spring:
  main:
    banner-mode: off

telegram:
  bot:
    token: 6531094812:AAH-XVCMzQfBlVpetG035gIsuW0YMrxD6GY
    name: Check AZ
    download-path: путь/к/установке/скачиванию